package com.example.localization

import androidx.compose.ui.unit.LayoutDirection
import com.example.model.AppLanguage

object Strings {
    private val en = mapOf(
        "app_title" to "Strike RGB CrossDroid",
        "app_version" to "1.0 CrossDroid",
        "author" to "KOUKOU",
        "rgb_led_status" to "RGB LED STATUS",
        "root_connected" to "Root Connected",
        "root_disconnected" to "Root Disconnected",
        "led_detected" to "RGB LED Detected",
        "led_not_detected" to "RGB LED Not Found",
        "active_mode" to "Active Mode",
        "brightness" to "Brightness",
        "running" to "Running",
        "stopped" to "Stopped",
        "start" to "START",
        "stop" to "STOP",
        "apply" to "APPLY",
        "save" to "SAVE",
        "reset" to "RESET",
        "cancel" to "CANCEL",
        "ok" to "OK",
        "request_root" to "REQUEST ROOT",
        "dynamic_color" to "Dynamic Color",
        "dynamic_color_desc" to "Adapt UI accent color to selected RGB LED",
        "start_on_boot" to "Start on Boot",
        "screen_color" to "Screen Color",
        "smooth_transition" to "Smooth Transition",
        "save_last_effect" to "Save Last Effect",
        "effect_speed" to "Effect Speed",
        "breathing_speed" to "Breathing Speed",
        "screen_sampling" to "Screen Sampling",
        "sensitivity" to "Sensitivity",
        "smoothing" to "Smoothing",
        "choose_led_color" to "Choose LED Color",
        "rgb_values" to "RGB Values",
        "home" to "Home",
        "effects" to "Effects",
        "color" to "RGB",
        "rgb" to "RGB",
        "light_flow" to "Light Flow",
        "aod" to "AOD",
        "settings" to "Settings",
        "general" to "General",
        "language" to "Language",
        "vibration_feedback" to "Tactile Vibration",
        "vibration_feedback_desc" to "Haptic feedback when toggling LEDs or picking color profiles",
        "color_profiles" to "Color Profiles",
        "color_profiles_desc" to "Curated vibrant RGB presets with tactile feedback",
        "appearance" to "Appearance",
        "root_hardware" to "Root & Hardware",
        "root_status" to "Root Status",
        "led_hardware" to "LED Hardware",
        "hardware_test" to "Hardware Test",
        "screen_sync" to "Screen",
        "startup" to "Startup",
        "start_last_effect_boot" to "Start Last Effect on Boot",
        "about" to "About",
        "version" to "Version",
        "author_label" to "Author",
        "default_effect" to "Default Effect",
        "speed" to "Speed",
        "sampling_rate" to "Sampling Rate",
        "root_dialog_title" to "Root Permission",
        "root_dialog_msg" to "Root access is required to control the RGB LED.",
        "unsupported_dialog_title" to "Unsupported Feature",
        "unsupported_dialog_msg" to "This feature is not available on this Android version.",
        "hardware_test_dialog_title" to "Running Hardware Test",
        "hardware_test_dialog_msg" to "Testing Red, Green, Blue channels and Strobe frequency...",
        "hardware_test_complete" to "Hardware Test Passed Successfully!",
        "design_identity" to "Google Stock Android 17 / Pixel UI Design",
        "theme_system" to "System Default",
        "theme_light" to "Light",
        "theme_dark" to "Dark",
        "theme_newbieui26" to "NEWBIEUI26",
        "theme_xml" to "XML",
        "matrix_battery_telemetry" to "Matrix Battery Dr & Telemetry",
        "battery_level" to "Battery Level",
        "battery_health" to "Hardware Health",
        "prismal_engine" to "Prismal RGB Engine Active",
        "battery_charging" to "Charging Active",
        "battery_discharging" to "On Battery Power",
        "ui_theme" to "UI Theme",
        "ui_theme_desc" to "Switch between Modern NewbieUI26 and Classic Android XML Theme",
        "effect_static" to "Static Color",
        "effect_breathing" to "Breathing",
        "effect_rainbow" to "Rainbow Cycle",
        "effect_strobe" to "Strobe Flash",
        "effect_wave" to "Wave Pulse",
        "effect_pulse" to "Heartbeat Pulse",
        "node_path" to "Sysfs Node: ",
        "uid_label" to "UID: 0 (Superuser)",
        "hardware_test_action" to "Run Channel Test",
        "applied_toast" to "RGB color and effect applied",
        "saved_toast" to "Settings saved to flash",
        "preset_colors" to "Pixel Palette",
        "root_access" to "Root Access",
        "root_access_desc" to "Root access allows Strike RGB CrossDroid to control the hardware RGB LEDs directly.",
        "root_status_title" to "Root Status",
        "root_granted" to "✓ Root Granted",
        "root_not_granted" to "✕ Root Not Granted",
        "root_denied" to "✕ Root Denied",
        "root_not_found" to "✕ Root Not Available",
        "root_error" to "✕ Root Command Failed",
        "root_revoked" to "✕ Root Permission Revoked",
        "check_root" to "CHECK ROOT",
        "test_led_access" to "TEST ROOT LED",
        "keep_led_screen_off" to "Keep LED active when screen is off",
        "keep_led_screen_off_desc" to "Runs hardware effects in background with partial wake lock",
        "root_mode" to "ROOT MODE",
        "non_root_mode" to "NON-ROOT MODE",
        "hardware_unavailable" to "HARDWARE UNAVAILABLE",
        "provider_label" to "Provider",
        "driver_chip" to "Driver / Chip",
        "channel_red" to "Red Channel",
        "channel_green" to "Green Channel",
        "channel_blue" to "Blue Channel",
        "channel_available" to "Available",
        "channel_unavailable" to "Unavailable",
        "effect_screen_sync" to "Screen Sync / Ambilight",
        "screen_sync_active" to "Screen Sync Active",
        "screen_sync_permission_denied" to "Screen capture permission was denied",
        "screen_sync_intensity" to "Sync Intensity",
        "screen_sync_boost" to "Color Boost",
        "screen_sync_boost_desc" to "Enhance color saturation and vibrancy on LED",
        "screen_sync_rate" to "Sampling Rate",
        "screen_sync_region" to "Sampling Region",
        "region_full_screen" to "Full Screen",
        "region_top" to "Top Screen Area",
        "region_center" to "Center Area",
        "region_bottom" to "Bottom Screen Area",
        "region_top_center" to "Top Center",
        "region_bottom_center" to "Bottom Center",
        "screen_sync_keep_off" to "Keep color when screen is off",
        "screen_sync_keep_off_desc" to "Maintains ambient color when phone display turns off",
        "screen_sync_debug" to "Live Ambilight Diagnostics",
        "detected_color" to "Detected Screen Color",
        "smoothed_led_color" to "Physical LED Color",
        "fps_counter" to "Sampling FPS",
        "grant_screen_permission" to "Grant Screen Capture Permission",
        "custom_background" to "Custom Background",
        "upload_image" to "Upload Image",
        "blur_intensity" to "Blur Intensity",
        "background_overlay" to "Background Overlay",
        "reset_background" to "Reset Background",
        "reset_background_confirm" to "Reset Custom Background?",
        "reset_background_desc" to "This will remove the uploaded background and restore the default system background.",
        "preview" to "Preview",
        "no_custom_bg" to "No custom background image selected",
        "bg_updated" to "Custom background updated",
        "notification_light_flow" to "Notification Light Flow",
        "notification_outputs" to "Notification Outputs",
        "output_rgb_only" to "RGB LED Only",
        "output_rear_flash_only" to "Rear Camera Flash Only",
        "output_front_screen_flash_only" to "Front / Screen Flash Only",
        "output_aod_only" to "AOD / Ambient Only",
        "output_rgb_rear_flash" to "RGB + Rear Flash",
        "output_rgb_front_flash" to "RGB + Front/Screen Flash",
        "output_rgb_aod" to "RGB + AOD",
        "output_rgb_flash_aod" to "RGB + Flash + AOD",
        "output_all" to "All Outputs Synchronized",
        "rear_camera_flash" to "Rear Camera Flash",
        "rear_camera_flash_desc" to "Synchronize rear flashlight with notification pulses",
        "front_flash" to "Front Flash Notification",
        "front_flash_auto" to "Auto (Hardware or Screen Flash)",
        "front_flash_hardware" to "Hardware Front Flash",
        "front_flash_screen" to "Screen Flash",
        "front_flash_disabled" to "Disabled",
        "screen_flash_title" to "Screen Flash",
        "screen_flash_desc" to "Full-screen bright flash matching notification color",
        "flash_pattern" to "Flash Pattern",
        "pattern_single" to "Single (ON - OFF)",
        "pattern_double" to "Double (ON - OFF - ON - OFF)",
        "pattern_triple" to "Triple (3 Pulses)",
        "pattern_heartbeat" to "Heartbeat (Double pulse + pause)",
        "pattern_strobe" to "Strobe (Rapid flashing)",
        "pattern_sos" to "SOS (... --- ...)",
        "flash_speed" to "Flash Speed",
        "speed_slow" to "Slow",
        "speed_normal" to "Normal",
        "speed_fast" to "Fast",
        "speed_very_fast" to "Very Fast",
        "flash_duration" to "Flash Duration",
        "duration_1s" to "1 Second",
        "duration_3s" to "3 Seconds",
        "duration_5s" to "5 Seconds",
        "duration_10s" to "10 Seconds",
        "duration_30s" to "30 Seconds",
        "duration_until_dismissed" to "Until Dismissed (Max 60s Failsafe)",
        "aod_notification" to "AOD / Ambient Notification",
        "aod_style_minimal" to "Minimal (Clock + Icon)",
        "aod_style_icon" to "Icon Only",
        "aod_style_color" to "Color Badge",
        "aod_style_glow" to "RGB Glow",
        "aod_style_full" to "Full Notification",
        "aod_color_auto" to "Auto App Color",
        "aod_color_notification" to "Notification Accent Color",
        "aod_color_custom" to "Custom Color",
        "screen_off_master" to "Notifications while screen is OFF",
        "screen_off_rgb_only" to "RGB LED Only",
        "screen_off_rgb_rear_flash" to "RGB + Rear Flash",
        "screen_off_rgb_front_screen" to "RGB + Front/Screen Flash",
        "screen_off_rgb_aod" to "RGB + AOD",
        "screen_off_rgb_rear_flash_aod" to "RGB + Rear Flash + AOD",
        "screen_off_everything" to "Everything (RGB + Flashes + AOD)",
        "device_capabilities" to "Device Hardware Capabilities",
        "camera_permission_required" to "Camera permission required for flashlight control",
        "grant_camera_permission" to "Grant Camera Permission",
        "notification_access_title" to "Notification Listener Access",
        "grant_notification_access" to "Grant Notification Access",
        "notification_access_desc" to "Required to detect incoming notifications from apps",
        "test_notification" to "TEST NOTIFICATION FLOW",
        "stop_test" to "STOP TEST",
        "app_profiles_title" to "App-Specific Profiles",
        "aod_unavailable" to "AOD unavailable on this device",
        "aod_unavailable_desc" to "Native Always-On Display is not supported on this display hardware. RGB and screen flash are active.",
        "theme_ultimate_liquid_glass" to "ULTIMATE NEWBIE LIQUID GLASS",
        "aod_title" to "Always On Display (AOD)",
        "aod_enable" to "Enable Always On Display",
        "aod_enable_desc" to "Ambient clock, battery telemetry, and notification lighting",
        "aod_themes" to "AOD Themes",
        "aod_theme_newbie_minimal" to "Newbie Minimal",
        "aod_theme_pixel" to "Pixel 17",
        "aod_theme_digital" to "Digital Horizon",
        "aod_theme_analog" to "Precision Analog",
        "aod_theme_neon" to "Neon Cyberpunk",
        "aod_theme_rgb" to "RGB Chroma",
        "aod_theme_aurora" to "Aurora Borealis",
        "aod_theme_liquid_glass" to "Prismal Liquid Glass",
        "aod_theme_edge_glow" to "Edge Glow Matrix",
        "aod_theme_ambient" to "Minimal Ambient",
        "aod_clock_customization" to "Clock Customization",
        "aod_clock_type" to "Clock Display Style",
        "aod_clock_size" to "Clock Size",
        "aod_clock_position" to "Clock Screen Position",
        "aod_24h" to "24-Hour Format",
        "aod_auto_color" to "Auto-Sync Color to Active LED",
        "clock_digital" to "Digital Clock",
        "clock_analog" to "Analog Clock",
        "clock_size_small" to "Compact",
        "clock_size_medium" to "Medium",
        "clock_size_large" to "Large",
        "clock_size_xlarge" to "Extra Large (iOS 26)",
        "aod_clock_style" to "Clock Render Engine",
        "aod_clock_weight" to "Clock Typographic Weight",
        "weight_thin" to "Thin",
        "weight_light" to "Light",
        "weight_regular" to "Regular",
        "weight_semibold" to "Semi-Bold",
        "weight_bold" to "Bold",
        "aod_style_liquid_glass" to "Liquid Glass (iOS 26)",
        "aod_style_pixel" to "Pixel Minimal",
        "aod_style_digital" to "Digital Horizon",
        "aod_style_analog" to "Precision Analog",
        "aod_clock_opacity" to "Glass Opacity",
        "aod_clock_blur" to "Glass Refraction Blur",
        "aod_clock_refraction" to "Optical Refraction Index",
        "aod_clock_gloss" to "Specular Gloss Glare",
        "aod_clock_glow" to "Internal Dispersion Glow",
        "aod_clock_thickness" to "Glass Depth / Thickness",
        "aod_bg_interaction" to "Dynamic Background Interaction",
        "aod_bg_dark_overlay" to "Ambient Dark Tint Overlay",
        "aod_bg_blur" to "Background Optical Blur",
        "aod_bg_brightness" to "Background Luminescence",
        "aod_bg_refraction" to "Background Glass Dispersion",
        "clock_pos_top" to "Top Aligned",
        "clock_pos_center" to "Center Aligned",
        "date_pos_below" to "Below Clock",
        "date_pos_above" to "Above Clock",
        "aod_date_customization" to "Date & Calendar Display",
        "aod_show_date" to "Show Date",
        "aod_battery" to "Battery Telemetry",
        "aod_battery_percent" to "Battery Percentage",
        "aod_battery_icon" to "Battery Icon",
        "aod_battery_ring" to "Circular Battery Ring",
        "aod_notifications" to "Notification Indicators",
        "aod_notifications_desc" to "Display floating icons & animated glow when apps notify",
        "aod_brightness" to "AOD Brightness",
        "aod_edge_glow" to "Edge Glow Illumination",
        "aod_edge_glow_desc" to "Luminous animated borders along screen edges",
        "aod_edge_position" to "Edge Position",
        "edge_pos_full" to "Full Screen Perimeter",
        "edge_pos_top" to "Top Edge Only",
        "edge_pos_bottom" to "Bottom Edge Only",
        "edge_pos_left" to "Left Edge Only",
        "edge_pos_right" to "Right Edge Only",
        "aod_edge_rgb" to "RGB Spectrum Wave",
        "aod_edge_thickness" to "Edge Width",
        "aod_edge_glow_radius" to "Glow Radius",
        "aod_edge_speed" to "Wave Pulse Speed",
        "aod_preview_fullscreen" to "TEST AOD FULLSCREEN",
        "aod_preview_title" to "AOD Live Theme Preview",
        "aod_preview_tap_exit" to "Tap anywhere to exit preview",
        "aod_screen_off_title" to "Hardware Display Engine",
        "aod_native_supported" to "Native OLED / Low-Power Ambient Display Verified",
        "aod_ambient_fallback" to "Optimized Ambient Screen Fallback Active (Safe for IPS/LCD)",
        "quality_level" to "Liquid Glass Optical Engine",
        "quality_level_desc" to "Adjust Fresnel reflection, refraction fidelity & shader performance",
        "quality_low" to "Low (Efficiency)",
        "quality_balanced" to "Balanced (Fresnel)",
        "quality_high" to "High (Full Prismal Glass)",
        "bg_default_oled" to "Pitch Dark Obsidian",
        "bg_solid" to "Solid Tone",
        "bg_gradient" to "Optical Gradient",
        "bg_custom_image" to "Custom Wallpaper",
        "aod_glow_effect" to "Specular Clock Glow",
        "aod_pulse_effect" to "Heartbeat Breathing Pulse",
        "aod_theme_management" to "AOD Theme Management",
        "aod_theme_management_desc" to "Choose from 10 built-in themes and customize clock, date, battery, and edge glow effects",
        "aod_reset_theme" to "Reset to Theme Default",
        "aod_reset_theme_desc" to "Revert adjustments to this theme's signature preset",
        "aod_tab_themes" to "Built-in Themes",
        "aod_tab_clock" to "Clock Style",
        "aod_tab_date" to "Date Display",
        "aod_tab_battery" to "Battery Telemetry",
        "aod_tab_edge" to "Edge Glow Effects",
        "battery_style" to "Battery Indicator Style",
        "battery_style_capsule" to "Liquid Glass Capsule",
        "battery_style_ring" to "Circular Radial Ring",
        "battery_style_bar" to "Minimal Under-Bar",
        "battery_style_percent_only" to "Percentage Only",
        "battery_style_icon_only" to "Icon Only",
        "date_style" to "Date Typography Style",
        "date_style_pill" to "Floating Glass Pill",
        "date_style_minimal" to "Clean Glowing Text",
        "date_style_glow" to "Prismal Specular Glow",
        "date_style_uppercase" to "Spaced Uppercase",
        "date_format" to "Date Display Format",
        "edge_anim" to "Edge Animation Pattern",
        "edge_anim_breathing" to "Breathing Wave",
        "edge_anim_pulse" to "Heartbeat Pulse",
        "edge_anim_wave" to "Traveling Chromatic Wave",
        "edge_anim_static" to "Static Perimeter Border"
    )

    private val fr = mapOf(
        "app_title" to "Strike RGB CrossDroid",
        "app_version" to "1.0 CrossDroid",
        "author" to "KOUKOU",
        "rgb_led_status" to "STATUT LED RVB",
        "root_connected" to "Root Connecté",
        "root_disconnected" to "Root Déconnecté",
        "led_detected" to "LED RVB Détectée",
        "led_not_detected" to "LED RVB Introuvable",
        "active_mode" to "Mode Actif",
        "brightness" to "Luminosité",
        "running" to "En Marche",
        "stopped" to "Arrêté",
        "start" to "DÉMARRER",
        "stop" to "ARRÊTER",
        "apply" to "APPLIQUER",
        "save" to "ENREGISTRER",
        "reset" to "RÉINITIALISER",
        "cancel" to "ANNULER",
        "ok" to "OK",
        "request_root" to "DEMANDER LE ROOT",
        "dynamic_color" to "Couleur Dynamique",
        "dynamic_color_desc" to "Adapter l'accent UI à la couleur LED active",
        "start_on_boot" to "Lancer au Démarrage",
        "screen_color" to "Couleur d'Écran",
        "smooth_transition" to "Transition Fluide",
        "save_last_effect" to "Sauvegarder Dernier Effet",
        "effect_speed" to "Vitesse d'Effet",
        "breathing_speed" to "Vitesse de Respiration",
        "screen_sampling" to "Échantillonnage Écran",
        "sensitivity" to "Sensibilité",
        "smoothing" to "Lissage",
        "choose_led_color" to "Choisir la Couleur LED",
        "rgb_values" to "Valeurs RVB",
        "home" to "Accueil",
        "effects" to "Effets",
        "color" to "Couleur",
        "settings" to "Paramètres",
        "general" to "Général",
        "language" to "Langue",
        "vibration_feedback" to "Vibration tactile",
        "vibration_feedback_desc" to "Retour haptique lors de l'activation des LED ou du choix de profils",
        "color_profiles" to "Profils de couleurs",
        "color_profiles_desc" to "Préréglages RVB avec retour tactile",
        "appearance" to "Apparence",
        "root_hardware" to "Root & Matériel",
        "root_status" to "Statut Root",
        "led_hardware" to "Matériel LED",
        "hardware_test" to "Test Matériel",
        "screen_sync" to "Écran",
        "startup" to "Démarrage",
        "start_last_effect_boot" to "Démarrer le dernier effet au boot",
        "about" to "À propos",
        "version" to "Version",
        "author_label" to "Auteur",
        "default_effect" to "Effet par Défaut",
        "speed" to "Vitesse",
        "sampling_rate" to "Fréquence d'Échantillonnage",
        "root_dialog_title" to "Permission Root",
        "root_dialog_msg" to "L'accès Root est requis pour contrôler la LED RVB.",
        "unsupported_dialog_title" to "Fonction Non Prise en Charge",
        "unsupported_dialog_msg" to "Cette fonctionnalité n'est pas disponible sur cette version Android.",
        "hardware_test_dialog_title" to "Test Matériel en cours",
        "hardware_test_dialog_msg" to "Test des canaux Rouge, Vert, Bleu et stroboscope...",
        "hardware_test_complete" to "Test matériel réussi avec succès !",
        "design_identity" to "Design Google Stock Android 17 / Pixel UI",
        "theme_system" to "Défaut du Système",
        "theme_light" to "Clair",
        "theme_dark" to "Sombre",
        "theme_newbieui26" to "NEWBIEUI26",
        "theme_xml" to "XML",
        "matrix_battery_telemetry" to "Télémétrie Matrix Battery Dr",
        "battery_level" to "Niveau de Batterie",
        "battery_health" to "Santé Matérielle",
        "prismal_engine" to "Moteur RGB Prismal Actif",
        "battery_charging" to "En Charge",
        "battery_discharging" to "Sur Batterie",
        "ui_theme" to "Thème UI",
        "ui_theme_desc" to "Basculer entre l'interface NewbieUI26 et le thème Android XML classique",
        "effect_static" to "Couleur Statique",
        "effect_breathing" to "Respiration",
        "effect_rainbow" to "Cycle Arc-en-ciel",
        "effect_strobe" to "Stroboscope",
        "effect_wave" to "Vague",
        "effect_pulse" to "Battement de Cœur",
        "node_path" to "Nœud Sysfs : ",
        "uid_label" to "UID : 0 (Superutilisateur)",
        "hardware_test_action" to "Lancer le test des canaux",
        "applied_toast" to "Couleur RVB et effet appliqués",
        "saved_toast" to "Paramètres sauvegardés",
        "preset_colors" to "Palette Pixel",
        "root_access" to "Accès Root",
        "root_access_desc" to "L'accès root permet à Strike RGB CrossDroid de contrôler directement le matériel LED RVB.",
        "root_status_title" to "Statut Root",
        "root_granted" to "✓ Root Accordé",
        "root_not_granted" to "✕ Root Non Accordé",
        "root_denied" to "✕ Root Refusé",
        "root_not_found" to "✕ Root Non Disponible",
        "root_error" to "✕ Échec Commande Root",
        "root_revoked" to "✕ Permission Root Révoquée",
        "check_root" to "VÉRIFIER LE ROOT",
        "test_led_access" to "TESTER LA LED ROOT",
        "keep_led_screen_off" to "Maintenir la LED avec écran éteint",
        "keep_led_screen_off_desc" to "Exécute les effets matériels en arrière-plan avec partial wake lock",
        "root_mode" to "MODE ROOT",
        "non_root_mode" to "MODE SANS ROOT",
        "hardware_unavailable" to "MATÉRIEL INDISPONIBLE",
        "provider_label" to "Fournisseur",
        "driver_chip" to "Pilote / Puce",
        "channel_red" to "Canal Rouge",
        "channel_green" to "Canal Vert",
        "channel_blue" to "Canal Bleu",
        "channel_available" to "Disponible",
        "channel_unavailable" to "Indisponible",
        "custom_background" to "Arrière-plan personnalisé",
        "upload_image" to "Importer une image",
        "blur_intensity" to "Intensité du flou",
        "background_overlay" to "Superposition d'arrière-plan",
        "reset_background" to "Réinitialiser l'arrière-plan",
        "reset_background_confirm" to "Réinitialiser l'arrière-plan personnalisé ?",
        "reset_background_desc" to "Cela supprimera l'arrière-plan importé et restaurera l'arrière-plan par défaut.",
        "preview" to "Aperçu",
        "no_custom_bg" to "Aucune image d'arrière-plan sélectionnée",
        "bg_updated" to "Arrière-plan personnalisé mis à jour"
    )

    private val ar = mapOf(
        "app_title" to "Strike RGB CrossDroid",
        "app_version" to "1.0 CrossDroid",
        "author" to "KOUKOU",
        "rgb_led_status" to "حالة مؤشر RGB",
        "root_connected" to "تم الاتصال بالروت",
        "root_disconnected" to "الروت غير متصل",
        "led_detected" to "تم اكتشاف عتاد RGB",
        "led_not_detected" to "لم يتم العثور على RGB",
        "active_mode" to "الوضع النشط",
        "brightness" to "السطوع",
        "running" to "قيد التشغيل",
        "stopped" to "متوقف",
        "start" to "تشغيل",
        "stop" to "إيقاف",
        "apply" to "تطبيق",
        "save" to "حفظ",
        "reset" to "إعادة ضبط",
        "cancel" to "إلغاء",
        "ok" to "موافق",
        "request_root" to "طلب صلاحية الروت",
        "dynamic_color" to "اللون الديناميكي",
        "dynamic_color_desc" to "تكييف لون واجهة المستخدم مع لون الإضاءة",
        "start_on_boot" to "التشغيل عند الإقلاع",
        "screen_color" to "لون الشاشة",
        "smooth_transition" to "انتقال سلس",
        "save_last_effect" to "حفظ التأثير الأخير",
        "effect_speed" to "سرعة التأثير",
        "breathing_speed" to "سرعة التلاشي",
        "screen_sampling" to "عينة الشاشة",
        "sensitivity" to "الحساسية",
        "smoothing" to "النعومة",
        "choose_led_color" to "اختر لون الإضاءة",
        "rgb_values" to "قيم RGB",
        "home" to "الرئيسية",
        "effects" to "التأثيرات",
        "color" to "اللون",
        "settings" to "الإعدادات",
        "general" to "عام",
        "language" to "اللغة",
        "vibration_feedback" to "الاهتزاز اللمسي",
        "vibration_feedback_desc" to "استجابة لمسية عند تبديل الإضاءة أو اختيار ملفات الألوان",
        "color_profiles" to "ملفات الألوان",
        "color_profiles_desc" to "إعدادات ألوان RGB مع استجابة لمسية",
        "appearance" to "المظهر",
        "root_hardware" to "الروت والعتاد",
        "root_status" to "حالة الروت",
        "led_hardware" to "عتاد الإضاءة",
        "hardware_test" to "فحص العتاد",
        "screen_sync" to "الشاشة",
        "startup" to "بدء التشغيل",
        "start_last_effect_boot" to "تشغيل التأثير الأخير عند الإقلاع",
        "about" to "حول التطبيق",
        "version" to "الإصدار",
        "author_label" to "المطور",
        "default_effect" to "التأثير الافتراضي",
        "speed" to "السرعة",
        "sampling_rate" to "معدل المعاينة",
        "root_dialog_title" to "صلاحية الروت",
        "root_dialog_msg" to "يلزم الحصول على صلاحية الروت للتحكم في إضاءة RGB.",
        "unsupported_dialog_title" to "ميزة غير مدعومة",
        "unsupported_dialog_msg" to "هذه الميزة غير متاحة في هذا الإصدار من أندرويد.",
        "hardware_test_dialog_title" to "جاري فحص العتاد",
        "hardware_test_dialog_msg" to "فحص قنوات الأحمر والأخضر والأزرق والوميض...",
        "hardware_test_complete" to "تم اجتياز فحص العتاد بنجاح!",
        "design_identity" to "تصميم Google Stock Android 17 / Pixel UI",
        "theme_system" to "افتراضي النظام",
        "theme_light" to "فاتح",
        "theme_dark" to "داكن",
        "theme_newbieui26" to "NEWBIEUI26",
        "theme_xml" to "XML",
        "matrix_battery_telemetry" to "بيانات بطارية Matrix والفحص",
        "battery_level" to "مستوى البطارية",
        "battery_health" to "صحة العتاد",
        "prismal_engine" to "محرك Prismal RGB نشط",
        "battery_charging" to "جاري الشحن",
        "battery_discharging" to "على طاقة البطارية",
        "ui_theme" to "سمة واجهة المستخدم",
        "ui_theme_desc" to "التبديل بين NewbieUI26 المعاصر وسمة Android XML الكلاسيكية",
        "effect_static" to "لون ثابت",
        "effect_breathing" to "تلاشي تنفسي",
        "effect_rainbow" to "قوس قزح",
        "effect_strobe" to "وميض متقطع",
        "effect_wave" to "موجة متتابعة",
        "effect_pulse" to "نبض القلب",
        "node_path" to "مسار Sysfs: ",
        "uid_label" to "UID: 0 (مستخدم فائق)",
        "hardware_test_action" to "بدء فحص القنوات",
        "applied_toast" to "تم تطبيق لون وتأثير RGB",
        "saved_toast" to "تم حفظ الإعدادات",
        "preset_colors" to "ألوان بكسل",
        "root_access" to "صلاحيات الروت",
        "root_access_desc" to "تسمح صلاحيات الروت لتطبيق Strike RGB CrossDroid بالتحكم المباشر في عتاد RGB LED.",
        "root_status_title" to "حالة الروت",
        "root_granted" to "✓ تم منح الروت",
        "root_not_granted" to "✕ لم يتم منح الروت",
        "root_denied" to "✕ تم رفض الروت",
        "root_not_found" to "✕ الروت غير متوفر",
        "root_error" to "✕ فشل أمر الروت",
        "root_revoked" to "✕ تم إلغاء صلاحية الروت",
        "check_root" to "فحص الروت",
        "test_led_access" to "فحص إضاءة الروت",
        "keep_led_screen_off" to "إبقاء الإضاءة عند إطفاء الشاشة",
        "keep_led_screen_off_desc" to "تشغيل التأثيرات عبر خدمة في الخلفية مع قفل تنشيط جزئي",
        "root_mode" to "وضع الروت",
        "non_root_mode" to "وضع بدون روت",
        "hardware_unavailable" to "العتاد غير متوفر",
        "provider_label" to "المزود",
        "driver_chip" to "المشغل / الشريحة",
        "channel_red" to "القناة الحمراء",
        "channel_green" to "القناة الخضراء",
        "channel_blue" to "القناة الزرقاء",
        "channel_available" to "متوفر",
        "channel_unavailable" to "غير متوفر",
        "custom_background" to "خلفية مخصصة",
        "upload_image" to "تحميل صورة",
        "blur_intensity" to "شدة الضبابية",
        "background_overlay" to "تعتيم الخلفية",
        "reset_background" to "إعادة ضبط الخلفية",
        "reset_background_confirm" to "إعادة ضبط الخلفية المخصصة؟",
        "reset_background_desc" to "سيؤدي هذا إلى إزالة الخلفية المحملة واستعادة خلفية النظام الافتراضية.",
        "preview" to "معاينة",
        "no_custom_bg" to "لم يتم تحديد صورة خلفية مخصصة",
        "bg_updated" to "تم تحديث الخلفية المخصصة"
    )

    private val ary = mapOf(
        "app_title" to "Strike RGB CrossDroid",
        "app_version" to "1.0 CrossDroid",
        "author" to "KOUKOU",
        "rgb_led_status" to "حالة ليد RGB",
        "root_connected" to "الروت مكونيكطي",
        "root_disconnected" to "الروت مامكونيكطيش",
        "led_detected" to "لقينا هاردوير ديال RGB",
        "led_not_detected" to "مالقيناش ليد RGB",
        "active_mode" to "المود لي خدام",
        "brightness" to "الضو (السطوع)",
        "running" to "خدام",
        "stopped" to "حابس",
        "start" to "خدم",
        "stop" to "حبس",
        "apply" to "أبليكي",
        "save" to "سجل",
        "reset" to "رجع الزيرو",
        "cancel" to "إلغاء",
        "ok" to "واخا",
        "request_root" to "طلب الروت",
        "dynamic_color" to "اللون الديناميكي",
        "dynamic_color_desc" to "واجهة التطبيق تبدل لونها مع لون الليد",
        "start_on_boot" to "خدم مع الديماراج",
        "screen_color" to "لون الشاشة",
        "smooth_transition" to "تحول سلس",
        "save_last_effect" to "سجل آخر إيفّي",
        "effect_speed" to "سرعة الإيفّي",
        "breathing_speed" to "سرعة التنفس",
        "screen_sampling" to "عينة الشاشة",
        "sensitivity" to "الحساسية",
        "smoothing" to "النعومة",
        "choose_led_color" to "عزل لون الليد",
        "rgb_values" to "قيم RGB",
        "home" to "الرئيسية",
        "effects" to "الإيفيات",
        "color" to "اللون",
        "settings" to "الإعدادات",
        "general" to "عام",
        "language" to "اللغة",
        "vibration_feedback" to "الفيبراسيون واللمس",
        "vibration_feedback_desc" to "اهتزاز خفيف ملي كتشعل/طفي الليد ولا كتختار لون جديد",
        "color_profiles" to "بروفايلات الألوان",
        "color_profiles_desc" to "ألوان RGB واجدة مع اهتزاز لمسي ممتع",
        "appearance" to "المظهر",
        "root_hardware" to "الروت والعتاد",
        "root_status" to "حالة الروت",
        "led_hardware" to "عتاد الليد",
        "hardware_test" to "تيست ديال الهاردوير",
        "screen_sync" to "الشاشة",
        "startup" to "الديماراج",
        "start_last_effect_boot" to "خدم آخر إيفّي فاش يطفى ويشعل التيليفون",
        "about" to "على التطبيق",
        "version" to "النسخة",
        "author_label" to "صاحب التطبيق",
        "default_effect" to "الإيفّي الافتراضي",
        "speed" to "السرعة",
        "sampling_rate" to "معدل المعاينة",
        "root_dialog_title" to "صلاحية الروت",
        "root_dialog_msg" to "خاص ضروري الروت باش نتحكمو فالليد ديال RGB.",
        "unsupported_dialog_title" to "ميزة مامدعوماش",
        "unsupported_dialog_msg" to "هاد الميزة ماخداش فهاد الفيرسيون ديال أندرويد.",
        "hardware_test_dialog_title" to "التيست ديال الهاردوير خدام",
        "hardware_test_dialog_msg" to "كنتيستيو الأحمر والأخضر والأزرق والوميض...",
        "hardware_test_complete" to "التيست ديال الهاردوير داز بنجاح تام!",
        "design_identity" to "ديزاين Google Stock Android 17 / Pixel UI",
        "theme_system" to "ديال السيستيم",
        "theme_light" to "مضوي (فاتح)",
        "theme_dark" to "مضلم (داكن)",
        "theme_newbieui26" to "NEWBIEUI26",
        "theme_xml" to "XML",
        "matrix_battery_telemetry" to "فحص بطارية Matrix والعتاد",
        "battery_level" to "نسبة الشحن",
        "battery_health" to "صحة البطارية",
        "prismal_engine" to "محرك Prismal شغال",
        "battery_charging" to "بيشحن دابا",
        "battery_discharging" to "خدام بالبطارية",
        "ui_theme" to "تيم ديال الواجهة",
        "ui_theme_desc" to "بدل بين تيم NewbieUI26 وتيم Android XML الكلاسيكي",
        "effect_static" to "لون فيكس",
        "effect_breathing" to "تنفس هادئ",
        "effect_rainbow" to "قوس قزح كيدور",
        "effect_strobe" to "فلاش كيضرب",
        "effect_wave" to "موجة خفيفة",
        "effect_pulse" to "نبضات قلب",
        "node_path" to "مسار Sysfs: ",
        "uid_label" to "UID: 0 (Superuser)",
        "hardware_test_action" to "دير تيست للقنوات",
        "applied_toast" to "تطبق لون وتأثير RGB",
        "saved_toast" to "تسجلو الإعدادات",
        "preset_colors" to "ألوان بكسل",
        "root_access" to "صلاحيات الروت",
        "root_access_desc" to "صلاحيات الروت كتعطي لـ Strike RGB CrossDroid القدرة باش يتحكم فـ ليدات RGB ديريكت.",
        "root_status_title" to "حالة الروت",
        "root_granted" to "✓ الروت معطي (مقبول)",
        "root_not_granted" to "✕ الروت ماتعطاش",
        "root_denied" to "✕ الروت ترفض",
        "root_not_found" to "✕ الروت ماكاينش فهاد التلفون",
        "root_error" to "✕ فشل أمر الروت",
        "root_revoked" to "✕ تسحبات صلاحية الروت",
        "check_root" to "قلب الروت",
        "test_led_access" to "تيستي ليد الروت",
        "keep_led_screen_off" to "خلي الليد شاعل واخا تطفى الشاشة",
        "keep_led_screen_off_desc" to "كيخدم التأثيرات فـ الباكجراوند عبر خدمة مع partial wake lock",
        "root_mode" to "مود الروت",
        "non_root_mode" to "مود بلا روت",
        "hardware_unavailable" to "الهاردوير ماكاينش",
        "provider_label" to "المصدر",
        "driver_chip" to "الدرايفر / الشريحة",
        "channel_red" to "قناة الحمر",
        "channel_green" to "قناة الخضر",
        "channel_blue" to "قناة الزرق",
        "channel_available" to "كاين",
        "channel_unavailable" to "ماكاينش",
        "custom_background" to "خلفية مخصصة",
        "upload_image" to "تيليشارجي تصويرة",
        "blur_intensity" to "قوة الضبابية",
        "background_overlay" to "تغطية الخلفية",
        "reset_background" to "رجّع الخلفية الأصلية",
        "reset_background_confirm" to "ترجّع الخلفية الأصلية؟",
        "reset_background_desc" to "غادي تمسح التصويرة وترجع الخلفية العادية ديال السيستيم.",
        "preview" to "معاينة",
        "no_custom_bg" to "ما كاينا حتى تصويرة مخصصة",
        "bg_updated" to "تم تبديل الخلفية بنجاح"
    )

    fun get(key: String, language: AppLanguage): String {
        val map = when (language) {
            AppLanguage.ENGLISH -> en
            AppLanguage.FRENCH -> fr
            AppLanguage.ARABIC -> ar
            AppLanguage.DARIJA -> ary
        }
        return map[key] ?: en[key] ?: key
    }

    fun getLayoutDirection(language: AppLanguage): LayoutDirection {
        return when (language) {
            AppLanguage.ARABIC, AppLanguage.DARIJA -> LayoutDirection.Rtl
            else -> LayoutDirection.Ltr
        }
    }
}
